from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
inc = [cwd]
group = DefineGroup('App_watch_demo', src, depend = [''], CPPPATH = inc,
                    LOCAL_CCFLAGS = '')
Return('group')
