from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
path = [cwd]
lib = [':Default_GCC9.2.1_M33_hard-fp.a']
group = DefineGroup('Drivers', src, depend = ['HR_USING_GH3018'], LIBS = lib, CPPPATH = path, LIBPATH = path)

Return('group')
